### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/web_and_cloud_group_13#1]
- [x] timing comparison (@everyone)
- [x] readme intro [@Amelia Tang](https://ubc-mds.slack.com/team/U02CMPRPGLE)
- [x] R EDA - reason why we chose the selected approach ([@Chaoran Wang](https://ubc-mds.slack.com/team/U02DJ54TB6C))
- [x] Python EDA  intro + reflection-1+ `dtype` ([@Junrong Zhu](https://ubc-mds.slack.com/team/U02CPL8EL9M) in both Python and R)
- [x] submission ([@Junrong Zhu](https://ubc-mds.slack.com/team/U02CPL8EL9M)) 
- [x] github repo (@zjr-mds )
- [x] team contract -> https://docs.google.com/document/d/1ANXtaNkJctWvbY645RifauygL7fTx1bi7hMorufJwOg/edit?pli=1
