### ISSUE TITLE
Milestone 2 tasks

### ISSUE THREAD

**Issue by zjr-mds** [UBC-MDS/web_and_cloud_group_13#26]
- [x] Uploading data @zjr-mds 
- [x] Data Wrangling @showcy 
- [x] Submission @showcy

**Comment by showcy** [comment]
- [x] To set up a collaborative environment
- [x] Setup your EC2 instance with JupyterHub.
- [x] Install all necessary things needed in your UNIX server (amazon ec2 instance).
- [x] Set up your S3 bucket.
- [x] Move the data that you wrangled in your last milestone to s3.
- [x] To move data from s3.
- [x] Wrangle the data in preparation for machine learning
- [x] Get the data from S3 in your notebook and make data ready for machine learning.

**Comment by showcy** [comment]
<img width="1207" alt="Screen Shot 2022-04-07 at 11 37 43 PM" src="https://user-images.githubusercontent.com/27760215/162378601-e76f51d2-c198-4e81-be73-6bbb00497f35.png">
